cook/cook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls', namespace='home')),
    path('pagin', include('pagination.urls', namespace='pagin')),

]

cook/pagination/urls.py
from django.urls import path
from . import views

app_name = 'pagin'
urlpatterns = [
    path('', views.pagin, name='home'),
]

cook/recipes/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.recipies_list, name='blog'),
    path('recipe/<name>', views.recipe, name='recipe'),

]

cook/pagination/models.py
from django.db import models

# Create your models here.

cook/recipes/models.py
from django.db import models

# Create your models here.

cook/pagination/views.py
from django.shortcuts import render
from . import csv_reader
from django.core.paginator import Paginator


def pagin(request):
    page_number = int(request.GET.get('page', 1))
    pag = Paginator(csv_reader.read_csv(), 10)
    page = pag.get_page(page_number)
    values = {
        'list': page,
        'title': 'Страница пагинации',

    }
    return render(request, 'pagination/index.html', values)

cook/recipes/views.py
from django.shortcuts import render
from . import form

DATA = {
    'omlet': {
        'яйца, шт': 2,
        'молоко, л': 0.1,
        'соль, ч.л.': 0.5,
    },
    'pasta': {
        'макароны, г': 0.3,
        'сыр, г': 0.05,
    },
    'buter': {
        'хлеб, ломтик': 1,
        'колбаса, ломтик': 1,
        'сыр, ломтик': 1,
        'помидор, ломтик': 1,
    }
}


def recipies_list(request):
    values = {
        'title': 'Список блюд',
        'list': DATA,

    }
    return render(request, 'recipes/index.html', values)


def recipe(request, name):
    count = request.GET.get('count')

    if count is not None:
        count = int(count)
        if count < 1:
            count = 1
    my_dict = dict()
    for k, v in DATA.items():
        if name == k:
            for keys, value in v.items():
                my_dict.setdefault(keys, value)
                if count is not None:
                    a = value * count
                    my_dict.update({keys: a})
            values = {
                'title': 'Рецепт',
                'my_dict': my_dict,
                'name': name,
                'form': form.form_for_number,
                'count': count,
            }
            return render(request, 'recipes/recipe.html', values)

cook/pagination/templates/pagination/index.html
{% extends 'recipes/base.html' %}


{% block body %}
<table class="table table-hover">
   <thead>
        <tr class="bg-success">
            <th>Name</th>
            <th>Street</th>
            <th>District</th>
        </tr>
   </thead>
    <tbody>
    {% for i in list %}
        <tr>
            <td>{{i.Name}}</td>
            <td>{{i.Street}}</td>
            <td>{{i.District}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="row ">
    <div class="col-4">
        {% if list.has_previous %}
            <p class="text-end"><a class="btn btn-primary " href="?page={{list.previous_page_number}}">Назад</a></p>
        {%  endif %}
    </div>
    <div class="col-4"><p class="text-center">Страница № {{list.number}}</p></div>
    <div class="col-4">
        {% if list.has_next %}
            <p class="text-start"><a class="btn btn-primary" href="?page={{list.next_page_number}}">Вперед</a></p>
        {%  endif %}
    </div>
</div>






{% endblock body %}

cook/recipes/templates/recipes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<center><h1>{{ title }}</h1></center>

{% block body %}{% endblock body %}
</body>
</html>

cook/recipes/templates/recipes/index.html
{% extends 'recipes/base.html' %}


{% block body %}
{% for k, v in list.items %}
<ul class="ul-list">
    <a href="recipe/{{k}}" class="list-group-item">{{ k.capitalize }}</a>
</ul>

{% endfor %}

<a href="{% url 'pagin:home' %}">Ссылка на пагинацию</a>
{% endblock body %}

cook/recipes/templates/recipes/recipe.html
{% extends 'recipes/base.html' %}
{% load crispy_forms_tags %}


{% block body %}
<a href="{% url 'home:blog' %}">Главная</a>
{% if count != None %}
<p class="text-warning text-center">
    Подсчет блюда {{name.capitalize}} для {{count}} персон
</p>
{% endif %}


<p class="text-primary">Название блюда: {{ name.capitalize }}</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>№ п/п</th>
            <th>Название ингредиента</th>
            <th>Количество</th>
        </tr>
    </thead>
    <tbody>
    {% for k, v in my_dict.items %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ k }}</td>
            <td>{{ v }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% if count == None %}
<form method="GET">
    <h2 class="text-center">Форма подсчета количества ингредиентов</h2>
    <div class="form_group">
    {% csrf_token %}
    {{form | crispy}}

    <input class="btn btn-success mt-2" type="submit" value="Рассчитать">
    </div>
</form>



{% endif %}

{% if count != None %}

<a href="{{name}}">Ввести другое значение</a>



{% endif %}

{% endblock body %}